Join cluster

diff --git a/templates/zs-bootstrap-puppet.sh.erb b/templates/zs-bootstrap-puppet.sh.erb
--- a/templates/zs-bootstrap-puppet.sh.erb
+++ b/templates/zs-bootstrap-puppet.sh.erb
@@ -5,25 +5,33 @@ ORDER_NUMBER=<%= scope.lookupvar('zendserver::license_name') %>
 LICENSE_KEY=<%= scope.lookupvar('zendserver::license_key') %>
 TARGET_NAME=localadmin
 CREATE_FACTS=<%= scope.lookupvar('zendserver::create_facts') %>
-
-/usr/local/zend/bin/zs-manage bootstrap-single-server -p $ADMIN_PASSWORD -o $ORDER_NUMBER -l $LICENSE_KEY -a TRUE > /usr/local/zend/tmp/zs-done
-WEB_API_KEY=`head -1 /usr/local/zend/tmp/zs-done | cut -f1`
-WEB_API_KEY_HASH=`head -1 /usr/local/zend/tmp/zs-done | cut -f2`
+BOOTSTRAP_OUTPUT_FILE='/usr/local/zend/tmp/zs-done'
 
 
-echo WEB_API_KEY=$WEB_API_KEY > /usr/local/zend/etc/zs-webapi-key.sh
-echo WEB_API_KEY_HASH=$WEB_API_KEY_HASH >> /usr/local/zend/etc/zs-webapi-key.sh
+#Include common functions
+source /usr/local/zend/bin/zs-puppet-common-functions.sh
 
-#Create target to be used by zs-client.phar
-/usr/local/zend/bin/php /usr/local/zend/bin/zs-client.phar addTarget --target=$TARGET_NAME --zskey=$WEB_API_KEY --zssecret=$WEB_API_KEY_HASH
+#Exit if running user is not root
+#if [[ $USER != 'root' ]] ; then echo "This script must be ran as root" ; exit 1 ; fi
 
-if $CREATE_FACTS == true 
-then
-	#Create web_api_key facts if required
-	FACTS_DIR=/etc/facter/facts.d
-	mkdir -p $FACTS_DIR && \
-	echo "zend_api_key_name=$WEB_API_KEY" > $FACTS_DIR/zend_api_key_name.txt
-	echo "zend_api_key_hash=$WEB_API_KEY_HASH" > $FACTS_DIR/zend_api_key_hash.txt
+#Make the script idempotent - 
+#Check if Zend Server is already bootstrapped
+ZEND_SERVER_BOOTSTRAPPED=`facter zend_gui_completed`
+if [[ $ZEND_SERVER_BOOTSTRAPPED == true ]] 
+then 
+  exit 0
+else
+  #Bootstrap Zend Server in single server mode
+  zs_manage_bootstrap_single || exit 1 #The whole script should fail if bootstrap failed
+  #Get web web api key from $BOOTSTRAP_OUTPUT_FILE
+  get_web_api_key_from_file &&\
+    create_web_api_key_wrapper_script &&\
+    create_zs_client_target
+  #Create target to be used by zs-client.phar
+
+  #Create web_api_key facts if required
+  if [ $CREATE_FACTS == true ]
+  then
+    create_facts
+  fi
 fi
-
-touch /usr/local/zend/tmp/zs-done
